name: sloppy-labwork
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.6
  - pip
  - pip:
    - Django==3.1
    - Markdown==3.3
    - Pillow==8.3
    - boto3==1.17
    - django-allauth==0.43
    - django-heroku==0.3
    - gunicorn==20.1
    - psycopg2-binary==2.9
    - requests
    - sendgrid==6.7
